### ISSUE TITLE
update to node v 20

### ISSUE THREAD

**Issue by calexil** [calexil/FightstickDisplay#83]
https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions

**Comment by calexil** [comment]
@benmoran56 

im lost I tried like 20 different ways to fix this pls halp

**Comment by benmoran56** [comment]
I think it's related to these versions:
```yml
    - uses: actions/checkout@v2
      ... 
      uses: actions/setup-python@v2
```

This is GitHub specific stuff. Changing them to something newer should work.
Try `setup-python@v5` and `checkout@v4`,  which I think are the newest (or at least new enough to satisfy GitHub).
